package batalhanaval;

public class JogoBatalhaNaval extends javax.swing.JFrame {

    BatalhaNaval batalhaNaval;

    /**
     * Creates new form JogoBatalhaNaval
     */
    public JogoBatalhaNaval() {
        initComponents();
        batalhaNaval = new BatalhaNaval();
        batalhaNaval.sortearNavios();
        batalhaNaval.dica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        painel_Campo = new javax.swing.JPanel();
        bloco_0_0 = new javax.swing.JLabel();
        bloco_0_1 = new javax.swing.JLabel();
        bloco_0_2 = new javax.swing.JLabel();
        bloco_0_3 = new javax.swing.JLabel();
        bloco_1_0 = new javax.swing.JLabel();
        bloco_1_1 = new javax.swing.JLabel();
        bloco_1_2 = new javax.swing.JLabel();
        bloco_1_3 = new javax.swing.JLabel();
        bloco_2_0 = new javax.swing.JLabel();
        bloco_2_1 = new javax.swing.JLabel();
        bloco_2_2 = new javax.swing.JLabel();
        bloco_2_3 = new javax.swing.JLabel();
        bloco_3_0 = new javax.swing.JLabel();
        bloco_3_1 = new javax.swing.JLabel();
        bloco_3_2 = new javax.swing.JLabel();
        bloco_3_3 = new javax.swing.JLabel();
        painel_topo = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        painel_controle = new javax.swing.JPanel();
        legenda = new javax.swing.JScrollPane();
        textoLegenda = new javax.swing.JTextArea();
        botao_atirar = new javax.swing.JButton();
        campo_linha = new javax.swing.JTextField();
        campo_coluna = new javax.swing.JTextField();
        display_linha = new javax.swing.JLabel();
        display_coluna = new javax.swing.JLabel();
        painel_feedback = new javax.swing.JPanel();
        feedback = new javax.swing.JScrollPane();
        textoFeedback = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel_Campo.setLayout(new java.awt.GridLayout(4, 4));

        bloco_0_0.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        bloco_0_0.setForeground(new java.awt.Color(51, 204, 255));
        bloco_0_0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloco_0_0.setText("~");
        painel_Campo.add(bloco_0_0);

        bloco_0_1.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        bloco_0_1.setForeground(new java.awt.Color(51, 204, 255));
        bloco_0_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloco_0_1.setText("~");
        painel_Campo.add(bloco_0_1);

        bloco_0_2.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        bloco_0_2.setForeground(new java.awt.Color(51, 204, 255));
        bloco_0_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloco_0_2.setText("~");
        painel_Campo.add(bloco_0_2);

        bloco_0_3.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        bloco_0_3.setForeground(new java.awt.Color(51, 204, 255));
        bloco_0_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloco_0_3.setText("~");
        painel_Campo.add(bloco_0_3);

        bloco_1_0.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        bloco_1_0.setForeground(new java.awt.Color(51, 204, 255));
        bloco_1_0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloco_1_0.setText("~");
        painel_Campo.add(bloco_1_0);

        bloco_1_1.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        bloco_1_1.setForeground(new java.awt.Color(51, 204, 255));
        bloco_1_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloco_1_1.setText("~");
        painel_Campo.add(bloco_1_1);

        bloco_1_2.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        bloco_1_2.setForeground(new java.awt.Color(51, 204, 255));
        bloco_1_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloco_1_2.setText("~");
        painel_Campo.add(bloco_1_2);

        bloco_1_3.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        bloco_1_3.setForeground(new java.awt.Color(51, 204, 255));
        bloco_1_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloco_1_3.setText("~");
        painel_Campo.add(bloco_1_3);

        bloco_2_0.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        bloco_2_0.setForeground(new java.awt.Color(51, 204, 255));
        bloco_2_0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloco_2_0.setText("~");
        painel_Campo.add(bloco_2_0);

        bloco_2_1.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        bloco_2_1.setForeground(new java.awt.Color(51, 204, 255));
        bloco_2_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloco_2_1.setText("~");
        painel_Campo.add(bloco_2_1);

        bloco_2_2.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        bloco_2_2.setForeground(new java.awt.Color(51, 204, 255));
        bloco_2_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloco_2_2.setText("~");
        painel_Campo.add(bloco_2_2);

        bloco_2_3.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        bloco_2_3.setForeground(new java.awt.Color(51, 204, 255));
        bloco_2_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloco_2_3.setText("~");
        painel_Campo.add(bloco_2_3);

        bloco_3_0.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        bloco_3_0.setForeground(new java.awt.Color(51, 204, 255));
        bloco_3_0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloco_3_0.setText("~");
        painel_Campo.add(bloco_3_0);

        bloco_3_1.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        bloco_3_1.setForeground(new java.awt.Color(51, 204, 255));
        bloco_3_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloco_3_1.setText("~");
        painel_Campo.add(bloco_3_1);

        bloco_3_2.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        bloco_3_2.setForeground(new java.awt.Color(51, 204, 255));
        bloco_3_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloco_3_2.setText("~");
        painel_Campo.add(bloco_3_2);

        bloco_3_3.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        bloco_3_3.setForeground(new java.awt.Color(51, 204, 255));
        bloco_3_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloco_3_3.setText("~");
        painel_Campo.add(bloco_3_3);

        Titulo.setFont(new java.awt.Font("TF2 Build", 1, 62)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 51, 153));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Batalha Naval");

        javax.swing.GroupLayout painel_topoLayout = new javax.swing.GroupLayout(painel_topo);
        painel_topo.setLayout(painel_topoLayout);
        painel_topoLayout.setHorizontalGroup(
            painel_topoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        painel_topoLayout.setVerticalGroup(
            painel_topoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        textoLegenda.setColumns(20);
        textoLegenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textoLegenda.setRows(5);
        textoLegenda.setText("-------------------Legenda-------------------\n~ - ÁGUA\n* - Tiro dado, nenhum navio\nX - Tiro dado, navio afundado");
        legenda.setViewportView(textoLegenda);

        botao_atirar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botao_atirar.setText("ATIRAR !");
        botao_atirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_atirarMouseClicked(evt);
            }
        });
        botao_atirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_atirarActionPerformed(evt);
            }
        });

        campo_linha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_linhaActionPerformed(evt);
            }
        });

        display_linha.setText("LINHA");

        display_coluna.setText("COLUNA");

        textoFeedback.setColumns(20);
        textoFeedback.setRows(5);
        feedback.setViewportView(textoFeedback);

        javax.swing.GroupLayout painel_feedbackLayout = new javax.swing.GroupLayout(painel_feedback);
        painel_feedback.setLayout(painel_feedbackLayout);
        painel_feedbackLayout.setHorizontalGroup(
            painel_feedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(feedback)
        );
        painel_feedbackLayout.setVerticalGroup(
            painel_feedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(feedback, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painel_controleLayout = new javax.swing.GroupLayout(painel_controle);
        painel_controle.setLayout(painel_controleLayout);
        painel_controleLayout.setHorizontalGroup(
            painel_controleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_controleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_controleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painel_feedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painel_controleLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(legenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_controleLayout.createSequentialGroup()
                        .addGroup(painel_controleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botao_atirar)
                            .addGroup(painel_controleLayout.createSequentialGroup()
                                .addGroup(painel_controleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campo_coluna)
                                    .addComponent(campo_linha, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painel_controleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(display_coluna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(display_linha, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(101, 101, 101))))
        );
        painel_controleLayout.setVerticalGroup(
            painel_controleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_controleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_controleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campo_linha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(display_linha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel_controleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campo_coluna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(display_coluna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botao_atirar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painel_feedback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(legenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painel_controle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painel_Campo, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painel_topo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painel_topo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painel_Campo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painel_controle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        

    public void atualizarTabAcertou(int i, int j) {
       
         if (i == 0 && j == 0) {
            bloco_0_0.setText("X");
        } else if (i == 0 && j == 1) {
            bloco_0_1.setText("X");
        } else if (i == 0 && j == 2) {
            bloco_0_2.setText("X");
        } else if (i == 0 && j == 3) {
            bloco_0_3.setText("X");
        } else if (i == 1 && j == 0) {
            bloco_1_0.setText("X");
        } else if (i == 1 && j == 1) {
            bloco_1_1.setText("X");
        } else if (i == 1 && j == 2) {
            bloco_1_2.setText("X");
        } else if (i == 1 && j == 3) {
            bloco_1_3.setText("X");
        } else if (i == 2 && j == 0) {
            bloco_2_0.setText("X");
        } else if (i == 2 && j == 1) {
            bloco_2_1.setText("X");
        } else if (i == 2 && j == 2) {
            bloco_2_2.setText("X");
        } else if (i == 2 && j == 3) {
            bloco_2_3.setText("X");
        } else if (i == 3 && j == 0) {
            bloco_3_0.setText("X");
        } else if (i == 3 && j == 1) {
            bloco_3_1.setText("X");
        } else if (i == 3 && j == 2) {
            bloco_3_2.setText("X");
        } else if (i == 3 && j == 3) {
            bloco_3_3.setText("X");
        }
    }

    public void atualizarTabErrou(int i, int j) {
        if (i == 0 && j == 0) {
            bloco_0_0.setText("*");
        } else if (i == 0 && j == 1) {
            bloco_0_1.setText("*");
        } else if (i == 0 && j == 2) {
            bloco_0_2.setText("*");
        } else if (i == 0 && j == 3) {
            bloco_0_3.setText("*");
        } else if (i == 1 && j == 0) {
            bloco_1_0.setText("*");
        } else if (i == 1 && j == 1) {
            bloco_1_1.setText("*");
        } else if (i == 1 && j == 2) {
            bloco_1_2.setText("*");
        } else if (i == 1 && j == 3) {
            bloco_1_3.setText("*");
        } else if (i == 2 && j == 0) {
            bloco_2_0.setText("*");
        } else if (i == 2 && j == 1) {
            bloco_2_1.setText("*");
        } else if (i == 2 && j == 2) {
            bloco_2_2.setText("*");
        } else if (i == 2 && j == 3) {
            bloco_2_3.setText("*");
        } else if (i == 3 && j == 0) {
            bloco_3_0.setText("*");
        } else if (i == 3 && j == 1) {
            bloco_3_1.setText("*");
        } else if (i == 3 && j == 2) {
            bloco_3_2.setText("*");
        } else if (i == 3 && j == 3) {
            bloco_3_3.setText("*");
        }
    }

    private void botao_atirarMouseClicked(java.awt.event.MouseEvent evt) {                                          
        int linha = Integer.parseInt(campo_linha.getText());
        int coluna = Integer.parseInt(campo_coluna.getText());
        if (batalhaNaval.verificarTiro(linha, coluna)) {
            textoFeedback.setText("Você acertou um navio, Parabéns!");
            atualizarTabAcertou(linha, coluna);
        } else {
            textoFeedback.setText("Você errou!");
            textoFeedback.setText(batalhaNaval.dica());
            atualizarTabErrou(linha, coluna);
        }
        
        
    }                                         

    private void campo_linhaActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void botao_atirarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoBatalhaNaval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoBatalhaNaval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoBatalhaNaval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoBatalhaNaval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoBatalhaNaval().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel bloco_0_0;
    private javax.swing.JLabel bloco_0_1;
    private javax.swing.JLabel bloco_0_2;
    private javax.swing.JLabel bloco_0_3;
    private javax.swing.JLabel bloco_1_0;
    private javax.swing.JLabel bloco_1_1;
    private javax.swing.JLabel bloco_1_2;
    private javax.swing.JLabel bloco_1_3;
    private javax.swing.JLabel bloco_2_0;
    private javax.swing.JLabel bloco_2_1;
    private javax.swing.JLabel bloco_2_2;
    private javax.swing.JLabel bloco_2_3;
    private javax.swing.JLabel bloco_3_0;
    private javax.swing.JLabel bloco_3_1;
    private javax.swing.JLabel bloco_3_2;
    private javax.swing.JLabel bloco_3_3;
    private javax.swing.JButton botao_atirar;
    private javax.swing.JTextField campo_coluna;
    private javax.swing.JTextField campo_linha;
    private javax.swing.JLabel display_coluna;
    private javax.swing.JLabel display_linha;
    private javax.swing.JScrollPane feedback;
    private javax.swing.JScrollPane legenda;
    private javax.swing.JPanel painel_Campo;
    private javax.swing.JPanel painel_controle;
    private javax.swing.JPanel painel_feedback;
    private javax.swing.JPanel painel_topo;
    private javax.swing.JTextArea textoFeedback;
    private javax.swing.JTextArea textoLegenda;
    // End of variables declaration                   


}
